---------------
-- WORKSHOP4 --
---------------

-- 1 --
SELECT NAME, HIRE, SAL FROM MEMBER 
WHERE DEPT_ID = (SELECT DEPT_ID FROM MEMBER WHERE NAME = '황기훈');
-- 2 --
SELECT MEMBER_ID, NAME FROM MEMBER
WHERE SAL > (SELECT AVG(SAL) FROM MEMBER);
-- 3 --
SELECT DEPT_ID, AVG(SAL) FROM MEMBER GROUP BY DEPT_ID
HAVING AVG(SAL) = (SELECT MAX(AVG(SAL)) FROM MEMBER GROUP BY DEPT_ID);
-- 4 --
SELECT NAME, SAL FROM MEMBER 
WHERE MGR = (SELECT MEMBER_ID FROM MEMBER WHERE NAME = '배기수');
-- 5 --
SELECT MEMBER_ID, NAME, DEPT_ID, JIKWI FROM MEMBER 
WHERE DEPT_ID = (SELECT DEPT_ID FROM DEPT WHERE DEPT_NAME = '영업부');
-- 6 --
SELECT * FROM MEMBER WHERE MEMBER_ID IN (SELECT DISTINCT MGR FROM MEMBER);
-- 7 --
SELECT * FROM MEMBER
WHERE MEMBER_ID NOT IN (SELECT DISTINCT MGR FROM MEMBER WHERE MGR IS NOT NULL);
-- 8 --
SELECT * FROM MEMBER WHERE HIRE > (SELECT HIRE FROM MEMBER WHERE NAME = '김주부');
-- 9 --
SELECT NAME, DEPT_ID, SAL FROM MEMBER 
WHERE (DEPT_ID, SAL) IN (SELECT DEPT_ID, SAL FROM MEMBER WHERE BONUS IS NOT NULL);
-- 10 --
SELECT * FROM MEMBER WHERE SAL > (SELECT MAX(SAL) FROM MEMBER WHERE JIKWI = '과장');
-- 11 --
SELECT * FROM MEMBER m
LEFT JOIN (SELECT DEPT_ID, AVG(SAL) "AS" FROM MEMBER GROUP BY DEPT_ID) S 
ON m.DEPT_ID = s.DEPT_ID
WHERE m.SAL > s."AS";
-- 12 --
INSERT INTO DEPT VALUES (60, '교육팀', 600); 
-- 13 --
UPDATE MEMBER SET SAL = 6000 WHERE NAME = '김지희';
-- 14 --
DELETE MEMBER WHERE NAME = '권민수';
SELECT * FROM MEMBER;
ROLLBACK;
SELECT * FROM MEMBER;
-- 15 --
SELECT MEMBER_ID, NAME FROM MEMBER WHERE SAL > (SELECT AVG(SAL) FROM MEMBER);

---------------
-- WORKSHOP5 --
---------------
DROP TABLE TEST;
-- 1 --
CREATE TABLE TEST
(
    ID      NUMBER(5),
    NAME    VARCHAR2(20)
);
SELECT * FROM TEST;
-- 2 --
ALTER TABLE TEST
    ADD( JOB VARCHAR2(10));
-- 3 --
ALTER TABLE TEST
    DROP COLUMN JOB;
SELECT * FROM TEST;
-- 4 --
ALTER TABLE TEST
    ADD CONSTRAINT pk PRIMARY KEY(ID);
-- 5 --
DESC TEST;
-- 6 --
ALTER TABLE TEST
    DROP CONSTRAINT pk;
    
----------
-- TEST --
----------

-- Q4 --
SELECT MEMBER_ID, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE), 2) FROM MEMBER;
-- Q5 --
SELECT DEPT_ID, COUNT(*) FROM MEMBER GROUP BY DEPT_ID HAVING DEPT_ID IS NOT NULL ORDER BY DEPT_ID;
-- Q6 --
SELECT DEPT_ID, AVG(SAL) FROM MEMBER GROUP BY DEPT_ID HAVING MAX(SAL) > 5000 ORDER BY DEPT_ID;
-- Q7 --
SELECT m.NAME, m.JIKWI, m.DEPT_ID, d.DEPT_NAME FROM MEMBER m JOIN DEPT d ON m.DEPT_ID = d.DEPT_ID WHERE d.DEPT_NAME = '총무부';
-- Q8 --
SELECT COUNT(DISTINCT MGR) FROM MEMBER;
-- Q9 --
SELECT NAME, HIRE FROM MEMBER WHERE DEPT_ID = (SELECT DEPT_ID FROM MEMBER WHERE NAME = '홍길동');