SELECT * FROM DEPT;
SELECT DEPT_NAME, DECODE(LOC_ID, 100, 'INCHEON', 200, 'SEOUL', 300, 'BUSAN', 'ETC') "LOC" FROM DEPT;
SELECT DEPT_NAME, CASE LOC_ID WHEN 100 THEN 'INCHEON' WHEN 200 THEN 'SEOUL' WHEN 300 THEN 'BUSAN' ELSE 'ETC' END "LOC" FROM DEPT;
SELECT COUNT(*), AVG(SAL), MAX(SAL), MIN(SAL), SUM(SAL) FROM MEMBER;
SELECT COUNT(BONUS), COUNT(NVL(BONUS, 0)) FROM MEMBER;
/* WORKSHOP2 */
SELECT * FROM MEMBER;
-- 1 --
SELECT SUM(SAL) "급여 총액", AVG(SAL) "급여 평균", MAX(SAL) "최고 급여", MIN(SAL) "최소 급여" FROM MEMBER;
-- 2 --
SELECT JIKWI "직위", COUNT(*) "직원 수" FROM MEMBER GROUP BY JIKWI;
-- 3 --
SELECT COUNT(DISTINCT MGR) "관리자 수" FROM MEMBER;
-- 4 --
SELECT COUNT(*) "총 직원 수",
COUNT(CASE WHEN TO_CHAR(HIRE, 'YYYY') = '2000' THEN 1 END) "2000 입사",
COUNT(CASE WHEN TO_CHAR(HIRE, 'YYYY') = '2001' THEN 1 END) "2001 입사",
COUNT(CASE WHEN TO_CHAR(HIRE, 'YYYY') = '2002' THEN 1 END) "2002 입사",
COUNT(CASE WHEN TO_CHAR(HIRE, 'YYYY') = '2003' THEN 1 END) "2003 입사"
FROM MEMBER;
-- 5 --
SELECT AVG(NVL(BONUS, 0)) "보너스 평균" FROM MEMBER;
-- 6 --
SELECT DEPT_ID "부서번호", AVG(SAL) "평균급여" FROM MEMBER GROUP BY DEPT_ID HAVING MAX(SAL) > 10000;
-- 7 --
SELECT M.NAME "이름", M.JIKWI "직위", M.DEPT_ID "부서번호", D.DEPT_NAME "부서이름" FROM MEMBER "M" JOIN DEPT "D" ON M.DEPT_ID = D.DEPT_ID WHERE D.DEPT_NAME = '영업부';
-- 8 --
SELECT M1.NAME "이름", M1.MEMBER_ID "사번", M2.NAME "관리자 이름", M2.MEMBER_ID "관리자 사번" FROM MEMBER "M1" LEFT JOIN MEMBER "M2" ON M1.MGR = M2.MEMBER_ID;
-- 9 --
SELECT M1.NAME "이름", M1.MEMBER_ID "사번", DECODE(M2.NAME, NULL, '없음', M2.NAME) "관리자 이름", DECODE(M2.MEMBER_ID, NULL, '없음', M2.MEMBER_ID) "관리자 사번" FROM MEMBER "M1" LEFT JOIN MEMBER "M2" ON M1.MGR = M2.MEMBER_ID;
-- 10 --
SELECT M1.NAME "이름", M1.HIRE "입사일", M2.NAME "관리자 이름", M2.HIRE "관리자 입사일" FROM MEMBER "M1" LEFT JOIN MEMBER "M2" ON M1.MGR = M2.MEMBER_ID WHERE M1.HIRE < M2.HIRE;
-- 11 --
SELECT M.NAME "이름", M.DEPT_ID "부서 번호", D.DEPT_NAME "부서 이름" FROM MEMBER "M" LEFT JOIN DEPT "D" ON M.DEPT_ID = D.DEPT_ID WHERE M.BONUS IS NOT NULL;

