---------------
-- WORKSHOP3 --
---------------

-- 1 --
SELECT ORD_NO, LINE_NO, ITEM_NO, ORD_QTY FROM PO_ORDER_DETAIL WHERE ORD_NO = '19971213' ORDER BY ORD_QTY;
-- 2 --
SELECT ORD_NO, TO_CHAR(ORD_DATE, 'YYYY-MM-DD') "ORDER_DATE"
FROM PO_ORDER_HEADER "OH" JOIN PO_SUPPLIER "S" ON OH.SUP_NO = S.SUP_NO 
WHERE TO_CHAR(OH.ORD_DATE, 'YYYY.MM') = '1997.12' AND S.SUP_NAME = 'LG전자'
ORDER BY ORD_DATE DESC;
-- 3 --
SELECT OD.ORD_NO, OD.ITEM_NO, I.ITEM_NAME, OD.ORD_QTY 
FROM PO_ORDER_DETAIL "OD" JOIN PO_ITEM "I" ON OD.ITEM_NO = I.ITEM_NO
WHERE OD.ORD_NO = '19971203' ORDER BY OD.ORD_NO ASC;
-- 4 --
SELECT OH.ORD_NO, S.SUP_NAME, S.SUP_PHONE
FROM PO_ORDER_HEADER "OH" JOIN PO_SUPPLIER "S" ON OH.SUP_NO = S.SUP_NO
WHERE OH.DELV_DATE IS NULL ORDER BY S.SUP_NAME ASC;
-- 5 --
SELECT EMP_DEP, MIN(EMP_NO) "???" FROM PO_EMPLOYEER 
GROUP BY EMP_DEP HAVING EMP_DEP IN ('구매팀', '외자팀', '홍보부') ORDER BY EMP_DEP;
-- 6 --
SELECT DISTINCT S.SUP_NAME, S.SUP_ADDR
FROM PO_ORDER_HEADER "OH" 
JOIN PO_SUPPLIER "S" ON OH.SUP_NO = S.SUP_NO
JOIN PO_EMPLOYEER "E" ON OH.ORD_EMP = E.EMP_NO
WHERE E.EMP_DEP = '홍보부' AND E.EMP_NAME = '박찬호' AND TO_CHAR(OH.ORD_DATE, 'YYYY') = '1997'
ORDER BY S.SUP_NAME ASC;
-- 7 --
SELECT SUM(I.UNIT_PRICE * OD.ORD_QTY) "???"
FROM PO_ORDER_HEADER "OH" 
JOIN PO_ORDER_DETAIL "OD" ON OH.ORD_NO = OD.ORD_NO
JOIN PO_SUPPLIER "S" ON OH.SUP_NO = S.SUP_NO
JOIN PO_ITEM "I" ON OD.ITEM_NO = I.ITEM_NO
WHERE S.SUP_NAME = 'LG전자' AND TO_CHAR(OH.DELV_DATE, 'YYYY.MM') = '1997.12';
-- 8 --
SELECT S.SUP_NAME, COUNT(*) "???"
FROM PO_ORDER_HEADER "OH"
JOIN PO_SUPPLIER "S" ON OH.SUP_NO = S.SUP_NO
WHERE OH.DUE_DATE < OH.DELV_DATE
GROUP BY S.SUP_NAME HAVING COUNT(*) >= 2;
-- 9 --
SELECT MAX(I.UNIT_PRICE) "?"
FROM PO_ORDER_HEADER "OH"
JOIN PO_ORDER_DETAIL "OD" ON OH.ORD_NO = OD.ORD_NO
JOIN PO_ITEM "I" ON OD.ITEM_NO = I.ITEM_NO;